override_id: test-sticky-with-param
name: Test Sticky With Param
priority: 1
targets:
  groups: []
  sites:
    - travelswire
tracking:
  ga4: null
  gtm: null
  google_ads: null
  facebook_pixel: null
  facebook_domain_verification: null
  custom: []
scripts:
  head:
    - id: digi-widget
      src: https://digi-widget.pages.dev/atl.widget.js
  body_start: []
  body_end: []
  before_footer: []
scripts_vars: {}
ads_config:
  interstitial: false
  interstitial_config:
    script_url: ""
    script_inline: ""
    trigger:
      type: delay
      delay_seconds: 5
      scroll_percent: 50
    frequency:
      type: once_per_session
      max_per_session: 1
    page_types:
      - all
    close_delay_seconds: 3
    device: both
    exclude_pages: []
  layout: standard
  ad_placements:
    - id: search-ads
      position: after-paragraph-1
      device: all
      sizes: {}
      desktopSizeConfig:
        ratio:
          x: 16
          y: 9
        range:
          minWidth: null
          maxWidth: null
          minHeight: null
          maxHeight: null
        customSizes: []
      mobileSizeConfig:
        ratio:
          x: 16
          y: 9
        range:
          minWidth: null
          maxWidth: null
          minHeight: null
          maxHeight: null
        customSizes: []
      code: |
        <div id="atl-arrow1"></div>
                <script>
                    window._atl_loadWidget('atl-arrow1',
                        { feedid: 'iLHNbVQ6k', auth: 'zqZGwZB5c3Ep', qs: 'subid=fbcmp1&count=6&obj_id=0' }, 'arrow1',
                        { qs: 'g_umk=img&g_imgrt=169&g_by=1&g_lo=1&g_mcol=1&g_title=none' });
                </script>
      page_types:
        - article
      exclude_pages: []
  _mode: replace
ads_txt: []
activation:
  query_param: ctype
  query_value: "12"
theme: {}
legal: {}
